### ISSUE TITLE
Error in element.py for PlainTextAreaElement

### ISSUE THREAD

**Issue by rfrobenius** [exelearning/iteexe#169]
Hello-
When creating a custom iDevice, I have utilized the PlainTextArea field/element. However I encountered an error when trying to go to edit the custom iDevice once it is placed within an exe section or node: IDevice broken: 'PlainTextAreaElement' object has no attribute 'height'

I discovered that the problem is related to the logging function in element.py line 677:
log.debug("renderEdit content="+self.field.content+
                  ", height="+unicode(self.height))

On my own development machine if I remove the last part referring to the height, the custom iDevice works properly. I tried changing the debug level in the .cfg file to "error" but that did not solve the problem. I will try to experiment with other debug levels to see if I can get it to work on the regular installed exe 2.1.1. I have it working on a second machine, so I will have to do some experimenting for sure.

**Comment by ignaciogros** [comment]
Thanks, @rfrobenius!

Could you check that commit?
